### ISSUE TITLE
Chrome browser does not start

### ISSUE THREAD

**Issue by skopanirov** [WileyLabs/teasy#11]
Running tests in chrome browser causes the following errors (chrome browser does not start):
````
14:00:31,315 ERROR SeleniumTestExecutionListener:178 - *****class java.lang.NoSuchMethodError occurred when initializing webdriver***** -- ERROR -- io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
14:00:36,315 ERROR SeleniumTestExecutionListener:182 - *****Try to wrap driver, count - 1 *****
14:00:36,315 ERROR SeleniumTestExecutionListener:178 - *****class java.lang.NoSuchMethodError occurred when initializing webdriver***** -- ERROR -- io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
14:00:41,297 ERROR SeleniumTestExecutionListener:182 - *****Try to wrap driver, count - 2 *****
14:00:41,297 ERROR SeleniumTestExecutionListener:178 - *****class java.lang.NoSuchMethodError occurred when initializing webdriver***** -- ERROR -- io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
14:00:46,297 ERROR SeleniumTestExecutionListener:182 - *****Try to wrap driver, count - 3 *****
14:00:46,297 ERROR SeleniumTestExecutionListener:178 - *****class java.lang.NoSuchMethodError occurred when initializing webdriver***** -- ERROR -- io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
14:00:51,299 ERROR SeleniumTestExecutionListener:182 - *****Try to wrap driver, count - 4 *****
14:00:51,300 ERROR SeleniumTestExecutionListener:178 - *****class java.lang.NoSuchMethodError occurred when initializing webdriver***** -- ERROR -- io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
14:00:51,302 ERROR TestContextManager:231 - Caught exception while allowing TestExecutionListener [com.wiley.autotest.spring.SeleniumTestExecutionListener@287f94b1] to prepare test instance [com.wiley.wcs.tests.functional.UI.UI.WCS_117_UI_AUTHORIZATION_1_SK@3745e5c6]
org.openqa.selenium.WebDriverException: *****Unable to wrap driver after 5 attempts!***** io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'WWL-20161128-I7', ip: '192.168.109.91', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_31'
Driver info: driver.version: unknown
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:185)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:228)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.NoSuchMethodError: io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.chrome(SeleniumTestExecutionListener.java:684)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.initWebDriver(SeleniumTestExecutionListener.java:477)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:165)
	... 29 more

org.openqa.selenium.WebDriverException: *****Unable to wrap driver after 5 attempts!***** io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'WWL-20161128-I7', ip: '192.168.109.91', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_31'
Driver info: driver.version: unknown

	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:185)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:183)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:228)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.NoSuchMethodError: io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.chrome(SeleniumTestExecutionListener.java:684)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.initWebDriver(SeleniumTestExecutionListener.java:477)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:165)
	... 29 more


java.lang.NullPointerException
	at com.wiley.autotest.selenium.AbstractSeleniumTest.initScreenshotWebDriverEventListener(AbstractSeleniumTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)

14:00:51,361 ERROR SeleniumTestExecutionListener:178 - *****class java.lang.NoSuchMethodError occurred when initializing webdriver***** -- ERROR -- io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
14:00:51,362  WARN TestContextManager:268 - Caught exception while allowing TestExecutionListener [com.wiley.autotest.spring.SeleniumTestExecutionListener@287f94b1] to process 'before' execution of test method [public void com.wiley.wcs.tests.functional.UI.UI.WCS_117_UI_AUTHORIZATION_1_SK.test_WCS_117_UI_AUTHORIZATION_1_SK()] for test instance [com.wiley.wcs.tests.functional.UI.UI.WCS_117_UI_AUTHORIZATION_1_SK@3745e5c6]
org.openqa.selenium.WebDriverException: *****Unable to wrap driver after 6 attempts!***** io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'WWL-20161128-I7', ip: '192.168.109.91', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_31'
Driver info: driver.version: unknown
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:185)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.beforeTestMethod(SeleniumTestExecutionListener.java:234)
	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:265)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestMethod(AbstractTestNGSpringContextTests.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.NoSuchMethodError: io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.chrome(SeleniumTestExecutionListener.java:684)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.initWebDriver(SeleniumTestExecutionListener.java:477)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:165)
	... 28 more

org.openqa.selenium.WebDriverException: *****Unable to wrap driver after 6 attempts!***** io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'WWL-20161128-I7', ip: '192.168.109.91', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_31'
Driver info: driver.version: unknown

	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:185)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.beforeTestMethod(SeleniumTestExecutionListener.java:234)
	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:265)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestMethod(AbstractTestNGSpringContextTests.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.NoSuchMethodError: io.github.bonigarcia.wdm.ChromeDriverManager.getInstance()Lio/github/bonigarcia/wdm/ChromeDriverManager;
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.chrome(SeleniumTestExecutionListener.java:684)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.initWebDriver(SeleniumTestExecutionListener.java:477)
	at com.wiley.autotest.spring.SeleniumTestExecutionListener.prepareTestInstance(SeleniumTestExecutionListener.java:165)
	... 28 more
````

**Comment by skopanirov** [comment]
The issue was caused by another POM file. Old version of framework was included there and it conflicted with Teasy. Removing old framework dependency from second POM resolved the issue.
