### ISSUE TITLE
NPE in AbstractBlock for NullElement case

### ISSUE THREAD

**Issue by vefimofff** [WileyLabs/teasy#151]
java.lang.NullPointerException
 at com.wiley.autotest.selenium.context.AbstractBlock.throwException(AbstractBlock.java:58)
 at com.wiley.autotest.selenium.context.AbstractBlock.<init>(AbstractBlock.java:18)

**Comment by Lao-Ax** [comment]
Hi. See https://github.com/WileyLabs/teasy/pull/152

**Comment by vefimofff** [comment]
@Lao-Ax cool, thanks!
